### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA


### POST User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Ali",
  "gender": "Male"
}

### PUT User
PUT http://localhost:8080/api/id?id=19&name=B9&gender=male
Content-Type: application/json

### GET User By Name And Gender
GET http://localhost:8080/api/users
Content-Type: application/json

### GET User By Id
GET http://localhost:8080/api/id/22
Content-Type: application/json

### DELETE User By Id
DELETE http://localhost:8080/api/id/21
Content-Type: application/json